---
version: 0.0.1
discoveryPort:
  name: DPAsASource
  description: Average car price in barcelona
  category: customer
  image: http://google.com
  autofillUserinfo: true
  tags: []
  extra: {}
inputPorts:
  - alias: car_input_port
    description: string
    tags: []
    extra: {}
    syncType: pull
    type: s3
    sourceUrn: urn:dv:datasource:0ec70f7b-0691-4059-a0ee-e00a49c62542
    entityId:
      alias: car_prices
      createEntity: true
      type: s3-bucket
      entityPath: s3://dp-input-bucket/mpay-tx/mpay-tx.csv
      entityVariables:
        - key: my_dynamic_year
          value: date-YYYYMMdd
      entityFilterPatternMatch: "*"
      sourceSchemaUrn: urn:dv:schema:9d4716d4
      projectSchemaUrn: urn:dv:schema:9d4716d6
      fileFormat: csv
      delimiter: ","
      header: true
      processingTimeColumn:
        - processing_time
      actualTimeColumn:
        - processing_time
      projection:
        - legal_entity
        - store_name
        - amount
        - payment_option
        - currency
  - alias: data-product-as-source
    description: string
    tags: []
    extra: {}
    syncType: pull
    type: dataproduct
    dataProductUrn: urn:dv:dataproduct:012d3d01-a17a-4b4c-9b85-7d4e7862bb1d
    filter: ""
    projection:
      - id
      - name
      - marks
      - modified
stateManagement:
  alias: car_prices
  refreshInterval: "*/10 * * * *"
  updateStrategy: append
  productStoreState:
    logicalSchema:
      properties:
        legal_entity:
          type: string
        store_name:
          type: string
        amount:
          type: int
        payment_option:
          type: string
        currency:
          type: string
    retentionVersions: "10"
  updateStrategyOptions:
    entityRef: ${urn:dv:datasource:6d4714c3}:1
    tags:
      - test
transformation:
- alias: Transform 1
  type: SQL
  description: Join input1 and input2 to get the actual member name
  query: select * from i1 inner join i2 on i1.id=i2.id
  references:
  - alias: input1
    sqlReference: i1
  - alias: input2
    sqlReference: i2
  - alias: input3input3input3input3input3input3input3input3input3input3
    sqlReference: i2i2i2i2i2i2i2i2i2i2ii2i2i2i2i2i2i2i2i2i2i2i2i2i2ii2i2i2i2i2i2i2i2i2i2i2i2i2i2ii2i2i2i2i2i2i2i2i2i2i2i2i2i2ii2i2i2i2i2i2i2i2i2i2i2i2i2i2ii2i2i2i2
- alias: Transform 2
  type: SQL
  description: Generate the sum of marks on a name level
  query: select name,sum(marks) from t1 group by name
  references:
  - alias: input1
    sqlReference: t1
- alias: Transform 3
  type: SQL
  description: Generate the sum of marks on a name level
  query: select name,sum(marks) from t1 group by name 
dataQualityCheck:
  RecordCountCheck:
    inputPort:
      - referenceAlias: car_prices
        expression: "=="
        number: 100
    stateManagement:
      referenceAlias: Test0001
      expression: "=="
      number: 100
  NullValueCheck:
    inputPort:
      - referenceAlias: car_prices
        checks:
          - column: amount
            expression: ">="
            number: 0.9
          - column: card_number
            expression: ">="
            number: 0.95
          - column: auth_code
            expression: ">="
            number: 0.9
    stateManagement:
      referenceAlias: Test0001
      checks:
        - column: amount
          expression: ">="
          number: 0.9
           UnacceptableTextValueCheck:
    inputPort:
      - referenceAlias: Test0001_input_port
        checks:
          - column: UnitOfMass
            valueList:
              - KG
              - kg
              - gm
              - gram
            number: 0.95
            expression: <=
          - column: UnitOfvolume
            valueList:
              - litre
              - gallon
              - barrel
              - pint
            number: 0.9
            expression: <=
    stateManagement:
      referenceAlias: Test0001
      checks:
        - column: UnitOfLength
          valueList:
            - metres
            - feet
            - miles
            - yards
          number: 0.9
          expression: <=
  UniquenessCheck:
    inputPort:
      - referenceAlias: Test0001_input_port
        checks:
          - column: unique_key1
          - column: unique_key2
  UniqueCombinationCheck:
    inputPort:
      - referenceAlias: Test0001_input_port
        checks:
          - columns:
              - colA
              - colB
          - columns:
              - colC
              - colD
    stateManagement:
      referenceAlias: Test0001
      checks:
        - columns:
            - Primary1
            - Primary2
        - columns:
            - Primary3
            - Primary4
  DistinctValueCountCheck:
    inputPort:
      - referenceAlias: Test0001_input_port
        checks:
          - column: CarCategory
            number: 7
            expression: <=
    stateManagement:
      referenceAlias: Test0001
      checks:
        - column: Gender
          number: 4
          expression: <=
